version: '3.8'
services:
  remotion-n8n:
    build: .
    ports:
      - "5678:5678"    # n8n
      - "3000:3000"    # Remotion Studio (if needed)
    volumes:
      - ./workflows:/app/workflows
      - ./downloads:/app/downloads
      - ./renders:/app/renders
      - ./remotion-projects:/app/remotion-projects
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=UTC
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 5
